version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: always
    # env_file:
        # - /tmp/mysql/.env
    # volumes: 
        # - mysql_log:/var/log
        # - /tmp/mysql/grant_privileges.sql:/docker-entrypoint-initdb.d/grant_privileges.sql
        # - /tmp/mysql/data:/var/lib/mysql
        # - /tmp/mysql/my.cnf:/etc/my.cnf
    ports:
        - 3307:3306
  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: my-test-app
  #     MYSQL_ROOT_PASSWORD: root
  #   # volumes:
  #   #   - ./docker/db:/docker-entrypoint-initdb.d
  #   ports:
  #       - "3306:3306"
  # db:
  #    image: mysql:5.7
  #    volumes:
  #      - /opt/test:/var/lib/mysql
  #      - ./mysql-dump:/docker-entrypoint-initdb.d
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: testdb1
  #      MYSQL_USER: testuser
  #      MYSQL_PASSWORD: root
  #    ports:
  #      - 3306:3306
  
  tomcat:
    depends_on:
      - mysql 
    # image: tomcat:9.0.12
    image: tomcat:8.5.73-jre8-temurin-focal
    container_name: tomcat
    volumes:
      # - /home/hitesh/compose-demo/tmp/tomcat.crt:/usr/local/tomcat/conf/tomcat.crt
      # - /home/hitesh/compose-demo/tmp/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      # - /home/hitesh/compose-demo/tmp/conf/server.xml:/usr/local/tomcat/conf/server.xml
      # - /home/hitesh/compose-demo/tmp/conf/web.xml:/usr/local/tomcat/conf/web.xml
      - /home/hitesh/compose-demo/tmp/sample:/usr/local/tomcat/webapps/sample
      # - /home/hitesh/compose-demo/tmp/keystore:/usr/local/tomcat/conf/.keystore


    # environment:
    # #   CATALINA_HOME: /opt/tomcat/
    ports:
      - "8443:8080"
    # command: