version: '3'
services:
  tomcat:
    image: tomcat:8.5.73-jre8-temurin-focal
    container_name: tomcat
    volumes:
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./webapps/sample:/usr/local/tomcat/webapps/sample
      - ./certs/identity.p12:/usr/local/tomcat/conf/identity.p12

    ports:
      - "8443:11000"
